services:
  kddice.game.api:
    image: kddice.game.api
    build:
      context: .
      dockerfile: KdDice.Game.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ASPNETCORE_URLS=http://+:80
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    name: kddice_network