apiVersion: v1
kind: Service
metadata:
  name: kd-dice-game-service
spec:
  type: LoadBalancer
  selector:
    app: kd-dice-game-api
  ports:
    - protocol: TCP
      port: 8080       # Accessible at localhost:8080
      targetPort: 80   # Matches containerPort in deployment